name: instant
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anndata=0.10.4=pyhd8ed1ab_0
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.9.0=19_linux64_openblas
  - libcblas=3.9.0=19_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libgomp=13.2.0=h807b86a_2
  - liblapack=3.9.0=19_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libsqlite=3.43.2=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - numpy=1.26.0=py310hb13e2d6_0
  - openssl=3.1.4=hd590300_0
  - pandas=2.1.1=py310hcc13569_1
  - pip=23.3.1=pyhd8ed1ab_0
  - python=3.10.12=hd12c33a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - tk=8.6.13=h2797004_0
  - tzdata=2023c=h71feb2d_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - contourpy==1.1.1
      - cycler==0.12.1
      - et-xmlfile==1.1.0
      - fonttools==4.43.1
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.8.0
      - openpyxl==3.1.2
      - packaging==23.2
      - pillow==10.1.0
      - psutil==5.9.6
      - pyparsing==3.1.1
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - threadpoolctl==3.2.0
      - pandas==2.1.4
      - anndata==0.10.4
